source 'https://rubygems.org'
gem 'rails', '4.1.4'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'simple_form','~>3.1.0'
gem 'bootstrap-sass', '3.2.0.2'
gem 'paperclip', '~> 4.2.1'
gem 'cocoon', '~> 1.2.6'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'haml'
gem 'spring',        group: :development